### ISSUE TITLE
Add TFT Display Support

### ISSUE THREAD

**Issue by linknum23** [micro-nova/AmpliPi#110]
- [x] Test and verify hardware interface works
- [x] Port OLED interface
- [x] Add the name of the selected stream for each source, as well as 'playing' status
- [x] Add volume bars for 6 zones
- [x] Add volume bars for 12 and 18 zones
- [x] Get touch events
- [x] Test out touch location capabilities
- [x] Add paged interface - there is only 1 page for now but the framework is there
- [x] If default AmpliPi API URL doesn't work, try the debug port 5000
- [x] Show errors on disconnect
- [x] Create service to launch at startup
- [x] Add to configure.py for setup
- [x] Add logging
- [x] Detect if not a Raspberry Pi or no display connected and quit
- [ ] Add documentation, maybe a little tutorial on debuging

Tabled until later:
- [ ] Does it work as a normal display?
- [ ] Investigate flickering when backlight is set to less than full brightness
- [ ] Create mock display for tests

**Comment by Lohrer** [comment]
Initial support added with Merge #131, remaining items will be addressed with #133
