### ISSUE TITLE
Adding hifi wifi wireless support using snapcast

### ISSUE THREAD

**Issue by Arndorferd** [micro-nova/AmpliPi#118]
The [Snapcast](https://github.com/badaix/snapcast) project could be used to add hifi wifi wireless support. I am curious if this could be baked into the pi already in the system and used as an easy extra feature just using other pis to receive.

**Comment by linknum23** [comment]
Snapcast is pretty awesome. The only issue, from a hardware perspective, is that the current version of AmpliPi is only capable of forwarding digital streams. We started talking about adding it in discussion #75, please continue the discussion there.
