### ISSUE TITLE
Improve automatic fan control

### ISSUE THREAD

**Issue by Lohrer** [micro-nova/AmpliPi#123]
It would be a good idea for the auto fan speed control to take into account as many temperature measurements available. I know there is the one on the power board and the raspberry pi has it's temperature too (see the front panel display code). I assume the amp board has a temp sensor too.

A simple method would just take the highest temp, maybe with slight adjustments to account for different expected temp ranges - the pi idles at ~45C, I doubt the power supply is that hot at idle. Then just take that number and input it into the fan curve as before.

A slightly more configurable option would be to have fan speed curves for all sources of temperature, then take the max of the outputs of each of those fan curves.

Or maybe there's an even better method!

**Comment by micronova-jb** [comment]
Temperature sensing on the Amp board is hardware controlled - when the amplifiers get hot, the fans will automatically attempt to stabilize the system. The only real control that can happen from a software perspective is setting the "FAN_OVERRIDE" bit in Preamp register 0x0C. Reading out from this register can give a fan failure status, as well as an over temp status

Some sort of service (Pi side) should be added that does a few things:
1. Check over temp / fan failure status and report this (maybe give a warning on the WebApp)
2. Read from the ADC on the power board to check for power supply temperature
3. Check the temperature of the Pi itself
4. Set FAN_OVERRIDE high when any of the temperatures are unsatisfactory by writing to the preamp board
