### ISSUE TITLE
Expansion Board Preamp Programming

### ISSUE THREAD

**Issue by micronova-jb** [micro-nova/AmpliPi#141]
We need to implement preamp-to-preamp flashing over UART.
UART pass through may work, if not a special firmware version may need to be implemented that knows how to program subsequent preamp boards. 

- [x] Flash from master to first expansion preamp
- [x] Flash multiple expansion units in a chain
- [x] Finalize and test the firmware changes to support expansion NRST/BOOT0 and UART passthrough control

**Comment by Lohrer** [comment]
Expansion units will be programmed by having the previous Preamp Board enter "UART Passthrough" mode. The STM32's UART1 and UART2 will forward any messages received to the other. This adds a small latency to any reads, but doesn't seem to affect the `stm32flash` program. I have verified that this works for at least 1 master + 2 expansion units in the expansion_prog branch. There is still some software cleanup to do but the hardware has been verified functional.

**Comment by Lohrer** [comment]
Expansion programming support added in PR #175
