### ISSUE TITLE
Feature: mDNS announcement

### ISSUE THREAD

**Issue by kaikreuzer** [micro-nova/AmpliPi#152]
For mDNS (aka Bonjour), a server announces the services it has to offer. I would expect the AmpliPi to announce a service type "_http._tcp", which then points to its REST API. Note that with mDNS, you can have multiple AmpliPis in your local network and all of them could be found (as their service broadcast includes their respective IP addresses).

Also see https://github.com/micro-nova/AmpliPi/issues/54#issuecomment-882888132

**Comment by linknum23** [comment]
I have a draft PR of support for this (here)[https://github.com/micro-nova/AmpliPi/pull/149]
