### ISSUE TITLE
Built-in Tests

### ISSUE THREAD

**Issue by linknum23** [micro-nova/AmpliPi#158]
Add built-in tests that can be run using the display. Initial tests: 

LED Board
- [x] All on/scroll

Preout or Amplifier Board
- [x] 6 Zone 50% volume/mute toggle

Preamp
- [x] Program preamp and connected expansion board
- [x] 4x2 sources on zone 1 (also zone 7 on expansion)
- [x] Poll/display 24V ADC + thermistors

Controller
- [x] Aux/SPDIF
- [x] Enet (ping micro-nova.com)

Manual (but instructions on screen)
- [x] Desktop
- [x] USB Power load
- [x] Bootload

**Comment by micronova-jb** [comment]
Will this be closed by #167 ?

**Comment by linknum23** [comment]
Closed now that built-int-tests have been merged
