### ISSUE TITLE
Update diagram and specifications

### ISSUE THREAD

**Issue by linknum23** [micro-nova/AmpliPi#159]
Several changes have been made to the system design since the start of the Kickstarter campaign. 

The major changes are:
- Updated design of the front and back panel,
- Added preamplified outputs
- Added SPDIF and microphone inputs,
- Updated to a touch-enabled color TFT display.

What needs to be updated?
- [x] https://github.com/micro-nova/AmpliPi/blob/0.1.4/docs/imgs/Signal_Diagram_with_Expansion_Out.png
       https://github.com/micro-nova/AmpliPi/blob/0.1.4/hw/diagrams/signal-diagram.png
       Updated to:
       https://github.com/micro-nova/AmpliPi/blob/main/hw/diagrams/signal_diagram.drawio.svg
- [x] https://github.com/micro-nova/AmpliPi/blob/0.1.4/hw/diagrams/amplipi-board-diagram.png
       Updated to:
       https://github.com/micro-nova/AmpliPi/blob/main/hw/diagrams/controller_boards_diagram.drawio.svg
- [x] https://github.com/micro-nova/AmpliPi/blob/0.1.4/hw/diagrams/zone-expander-board-diagram.png
       Updated to:
       https://github.com/micro-nova/AmpliPi/blob/main/hw/diagrams/expander_boards_diagram.drawio.svg
- [x] https://github.com/micro-nova/AmpliPi/blob/0.1.4/hw/diagrams/high-level-diagram.jpg
       Updated to:
       https://github.com/micro-nova/AmpliPi/blob/main/hw/diagrams/rear_panel_labelled.drawio.svg
- [x] https://github.com/micro-nova/AmpliPi/blob/0.1.4/hw/diagrams/internals-diagram.jpg
       Updated to:
       https://github.com/micro-nova/AmpliPi/blob/main/hw/diagrams/internals_photo_labelled.drawio.svg
- [x] Update website with above images and specification
  - [x] Update website with diagram changes
  - [x] Update website with controller unit changes
  - [x] Update website with expansion unit changes

**Comment by Lohrer** [comment]
Mahdee updated the store page with the new pictures, anything else to be done here @linknum23?

**Comment by brianhealey** [comment]
How can one tell which hardware version they have?

**Comment by gorski123** [comment]
> How can one tell which hardware version they have?

@brianhealey Check here: https://github.com/micro-nova/AmpliPi/blob/main/hw/sch/hw_releases.md

In general, any main unit serial number > 128 will be the latest hardware rev.
