### ISSUE TITLE
Merge android app and preamp code into this repository to create a full everything amplipi repo

### ISSUE THREAD

**Issue by linknum23** [micro-nova/AmpliPi#19]
- [x] Add latest preamp firmware
- [x] Cleanup register interface documentation
- [x] Add GPL text to each of the .c modules and .h header files
- [ ] Add WIP version of android app

**Comment by linknum23** [comment]
@micronova-jb can you cleanup the firmware a little bit and put it in the folder fw in a branch and make a PR for it?

**Comment by micronova-jb** [comment]
Working on cleanup now - how much of the extra stuff should I include? I'm going to include the src, inc, and startup folders for sure. Should I also include StdPeriph_Driver, Debug/Release, extra documentation, etc?

**Comment by linknum23** [comment]
I think the idea is to include whatever is needed to reproduce a build. We
already have a binary for the current build checked in.

**Comment by linknum23** [comment]
Not planning to merge Android app, it is too out of sync with current API for this to make sense
