### ISSUE TITLE
Improved fan control

### ISSUE THREAD

**Issue by Lohrer** [micro-nova/AmpliPi#197]
Current fan control is on/off only. Choose and implement at least 1 of the following control methods:
- ~30 Hz PWM. Allows ~30-100% fan speed control. Requires extra capacitor on amp board to reduce audible noise.
- Hi/Low with an extra resistor and mosfet. Allows 100% and one other fan speed (50%?). Will need to use open-drain output on GPIO expander that used to be OVR_TMP.
- Linear control with DPOT. Allows ~50-100% fan speed control. This would be the best, but requires a non-isolated supply so we can adjust the voltage output.

Investigate any extra noise added to speaker outputs with all of these methods.

**Comment by stoppablemurph** [comment]
this would definitely be nice to have. the fans aren't running particularly often, but they're fairly loud when they do kick on.

**Comment by linknum23** [comment]
A couple notes on fan noise:
- We assumed most of the AmpliPi devices would be put in peoples server closets. From the feedback we are getting many of these are being put in main living areas. In this issue we are working on firmware and hardware modifications to reduce the fan noise.
- We are working on controlling the fan in the power supply itself, which has an aggressive fan that only has 2 modes full speed or off. The power supply fan at full speed is likely the loud fan noise you are hearing.

**Comment by stoppablemurph** [comment]
If hardware modifications are required for the chosen solution, will there be any kind of retrofit process for people who have units from before? (Or some kind of guide to make the necessary modifications or something)

**Comment by Lohrer** [comment]
The firmware I'm testing now will use PWM to reduce fan speed for the [hardware in our second batch of units](https://github.com/micro-nova/AmpliPi/blob/main/hw/sch/hw_releases.md#early-bird-units-and-kickstarter-campaign-part-1). The readme for the preamp's firmware documents how to flash the firmware but we'll definitely add a simpler guide, probably under [docs](https://github.com/micro-nova/AmpliPi/tree/main/docs), for firmware updates. In the future we'd love to get firmware updates integrated into the main software update flow (#144).

The power supply fan is trickier since we don't currently control it directly. We're working on a solution for the next rev of hardware and we can make a guide for whatever is required to retrofit older hardware.

**Comment by Lohrer** [comment]
Done in PR #212. Firmware v1.4 contains these changes and is included in AmpliPi release 0.1.7. AmpliPi updates now flash firmware so simply using the updater will update with these fan changes.

The first batch of 5 units (with Power Board Rev2) is unaffected as they use the MAX6644 fan controller. The second batch (with Power Board Rev3) get the new PWM control directly from the Preamp's micro, but the PSU fan is unaffected. All newer units have Power Board Rev4 with linear voltage fan control and a new PSU fan connector.

Updating older hardware to have the PSU fan controlled by the Power Board will take some creativity. If we come up with a solution it'll be posted here and on Discourse.
