### ISSUE TITLE
Bug: Spotify disconnect issues

### ISSUE THREAD

**Issue by Lohrer** [micro-nova/AmpliPi#214]
When a user disconnects Spotify (selects some other device to play on instead of AmpliPi) the last played song title and album art still show up in the web interface of AmpliPi. This would seem to imply if the "play" button is clicked that it should continue playing the last song, however this doesn't work because Spotify is disconnected.

I would suggest at least clearing the album art and song info on a disconnect, and possibly removing the "previous"/"play"/"next" controls. Check out spot_meta.py to add support for this. Some new state information will probably be needed for the concept of being connected to a client.

**Comment by linknum23** [comment]
This appears to be fixed by the spotifyd integration. Closing for now.
