### ISSUE TITLE
Feature - Connection Monitoring

### ISSUE THREAD

**Issue by linknum23** [micro-nova/AmpliPi#267]
Add connection monitoring to the web app to show the user that they are disconnected from AmpliPi

**Comment by linknum23** [comment]
We should also add support for time synchronization checking here, comparing amplipi and the web browsers time and alerting the user if they are off by more than a minute.
Time getting out of sync can cause all sorts of hard to troubleshoot issues..

**Comment by rtertiaer** [comment]
This has been implemented with the new ui :sunglasses:
