### ISSUE TITLE
Add AmpliPi interface to Sonoff Touch Panel

### ISSUE THREAD

**Issue by linknum23** [micro-nova/AmpliPi#298]
- [x] Checkout development process
  - [x] UI Changes
  - [x] ESP32 FW Changes
- [x] Add basic status polling interface to amplipi (kjk2010 did this here https://github.com/kjk2010/AmpliPi-POE-Touchscreen)
- [x] Add song info display
- [x] Add volume control  
- [x] Add OTA Updates
  - [x] Controller FW
  - [x] Display FW
- [x] Put one on the wall 
- [x] Testing
- [ ] Automatic AmpliPi discovery
- [x] Group control
- [ ] Horizontal view/mode
~~- Add album art?~~ Not possible in the current Panel

**Comment by linknum23** [comment]
Lots of info can be found in this thread: https://community.home-assistant.io/t/sonoff-nspanel-smart-scene-wall-switch-by-itead-coming-soon-on-kickstarter/332962/48

**Comment by brianhealey** [comment]
Are you planning on using espHome or directly interfacing with the ampliPi?

**Comment by linknum23** [comment]
For the initial port we are interfacing with it directly (using
micropython) but we are open to integrating with esphome as well.

**Comment by yoggiland** [comment]
Hi,
I understand that there are two versions, a US and an EU. From what I read they are different do to screen rotation etc. see link.

https://community.openhab.org/t/nxpanel-replacement-firmware-for-sonoff-nspanel/132869/72
https://community.openhab.org/t/nxpanel-replacement-firmware-for-sonoff-nspanel/132869

I am guessing you have the US version, do you think your current approach (using micropython) will work with the EU version?

yoggi

**Comment by linknum23** [comment]
We don't have an EU version on hand yet but it looks like it UI will just need a couple of layout changes from the US version. The EU and US versions share the same hardware, just with different power inputs and display resolutions. The backend running on micropython will hopefully be the exact same.

**Comment by rickballard** [comment]
When do you guys expect to be able to sell some of these wonderful wall keypads, to eager customers, like myself?  Can you be persuaded to sell off some of your prototypes for testing...?

**Comment by linknum23** [comment]
Based on where we are right now (a working prototype). I would guess we
will have the code available in a month for those that want to load the
code on the devices themselves.

As for the having them on our website with a finalized AmpliPi touch
interface, I would guess they would be available in 3-6 months.

**Comment by rickballard** [comment]
You do realize that we are all loving you guys up here, like a feast for starving piglets...?  :)

**Comment by linknum23** [comment]
We are getting close to being able to sell [these](https://www.micro-nova.com/amplipi/store/amplipi-in-wall-wifi-touchscreen-controller-with-integrated-2-device-switch) and will be making the related repo public in the next couple of days!

**Comment by brianhealey** [comment]
Let me know if you need a tester.  I have the US version in hand and can flash it easily.

**Comment by rickballard** [comment]
Yes, please, a tester would be wonderful, thank you.  It looks excellent.  

I particularly like the WiFi-ness, as legacy Cat \-wiring tends to make folks think of the keypad as being zone-specific, (even though this keypad can control all zones from a single location).  You might sell more keypads if they can be set to display a default zone dashboard, then folks might buy one per zone instead.  

Also, those hard-buttons are just itching to have a default smart-home purpose in life.  Please consider this idea:

Post simple instructions, so folks can add the circuit out of a cheap Lutron On-Off Pico, to be operated by those two (spare) hard-buttons.  This could add $100 in value to those folks who already have smart-lighting, at the cost of a few extra bucks for the Pico and 5-minutes of soldering/reassembly.  Alternatively, you guys could more formally ask Lutron to let the keypad talk to their hub via WiFi, and then there would be no hacking necessary.  

Those buttons are just itching to have a default smart-home purpose in life.

**Comment by linknum23** [comment]
These touch panels are actually available for sale, now!  Feel free to purchase one and let us know how it works.

As for the hard buttons: at the moment the hard buttons are able to control two led light circuits using twon onboard relays. The intent is that this could replace a single or dual light switch in your house simply by removing the switch and wiring in this wall panel in place.
We are hoping to expose them as smart switches in the future so they can be controlled by something like home assistant.

> Also, those hard-buttons are just itching to have a default smart-home purpose in life. Please consider this idea:

I'm not sure if connecting the output of one of the wallpanel's relays to a pico will do what you want. Hopefully we can add the Smart Home use case soon.

**Comment by linknum23** [comment]
Does anyone know of a simple MQTT light interface that we can provide for the 2 relays?

**Comment by brianhealey** [comment]
I use homeassistant with the mqtt addon to run most of my tasmota devices. would that work?

**Comment by rickballard** [comment]
OK, purchased, will let you know how it works up here in Canada.  I plan to turn it into a weather-resistant remote, that rests in a dock on an outside wall.  I can hide it inside in the winter, so the Polar Bears don't eat it, but it may have to cope with some hot and humid weather this summer.  Thanks.

**Comment by linknum23** [comment]
Looking at the panel specifications it is definitely intended for indoor use.

![2022-06-02_641x291](https://user-images.githubusercontent.com/628667/171711774-49b7c381-958f-43c2-88d4-2a4c6595359f.png)

**Comment by rickballard** [comment]
Touch panel works as advertised!  However, have not yet figured out how to 
a) link the ewelink app to the panel so that the hard buttons can be set to operate other sonoff/ewelink-compatible devices, like other separate mains-power relays.
b) link the panel to the phone via bluetooth, because the bluetooth discover phase of the power-up cycle seems to have been bypassed by the AmpliPi software load. 
c) Meanwhile, I noticed that if the Amplipi app is running on my phone, the panels seem to get ignored, or they work so slowly that I have not yet been patient enough to wait for them to respond.

**Comment by linknum23** [comment]
Closing this since the panel's repo is public now. Check it out at micro-nova/AmpliPiWallPanel/
