### ISSUE TITLE
Radio streams won't play

### ISSUE THREAD

**Issue by 0lek** [micro-nova/AmpliPi#300]
Hey,

So I encountered the following issue. It's not a biggie, but still want to mention this. I play an internet radio. Then I mute it. Then after time x (e.g. next day) I open the web app, want to play, but nothing comes out of the speakers. I need to change to another stream, this plays and then switch back.

Aleks

**Comment by linknum23** [comment]
Thanks for the heads up. We have the beginnings of a prototype to fix this in #297.

**Comment by linknum23** [comment]
Mostly fixed in #297. Also added a play/stop button to reflect current state and make it simpler to restart a radio station that still has issues.
