### ISSUE TITLE
Fix power supply override and document power register

### ISSUE THREAD

**Issue by Lohrer** [micro-nova/AmpliPi#304]
The 9V and 12V power supplies have an enable input that preamp_i2c_regs.md says is controllable but the firmware will in fact always immediately turn the supplies back on. There's not much reason to ever turn off the 9V or 12V, so alternatively maybe these bits should be read-only.

Once a decision is made over control, create better documentation and update any existing documentation.

**Comment by Lohrer** [comment]
The 9V enable is only present on old hardware, and the 12V fan power should always remain on. This register should be changed to be read-only.

**Comment by linknum23** [comment]
@Lohrer did this get fixed?

**Comment by Lohrer** [comment]
The work was done in #340, and the last bit of documentation was fixed in #452
