### ISSUE TITLE
Validate fields when creating stream

### ISSUE THREAD

**Issue by Lohrer** [micro-nova/AmpliPi#346]
Spotify and Airplay and potential other streams use the name as the "device name" to connect to. Spotify doesn't support `'` at least, and probably a lot more special characters. Likely AirPlay has invalid characters too. We need to figure out what's valid and then validate the config inputs so there user doesn't just get a silent error.

When running `journalctl  -f` to see the log output I get
```
authbind[766]: vollibrespot v0.2.4 61563b7 2021-07-22 (librespot 08d8bcc 2020-10-07) -- Built On 2021-07-22
authbind[766]: Reading Config from "config.toml"
authbind[766]: Malformed config key: expected newline, found an identifier at line 4 column 22
```

**Comment by linknum23** [comment]
This has a couple of subtasks
- [ ] Make stream creation throw an exception when a field in invalid
- [ ] return an http response when there is an exception, is there a standard way to do this for form submissions?
- [ ] which fields make sense to validate for each stream?
  - [ ] Pandora - pianobar
  - [ ] Spotify - spotifyd
  - [ ] Airplay - shairport-sync
  - [ ] Internet radio - vlc
  - [ ] LMS - squeezelite
