### ISSUE TITLE
Wallpad update

### ISSUE THREAD

**Issue by rickballard** [micro-nova/AmpliPi#359]
Getting "Syntax error on JSON" when attempting to update the Sonoff wall pad from 0.2.0, to either of the latest updates.  These errors then offer up a reboot button for the wallpad, because the wallpad is otherwise frozen.  It then returns back to its pre-update condition with 0.2.0.  Meanwhile, the Amplipi itself is running the latest, and working fine.  Any suggestions on how to proceed would be much appreciated.  Thanks.

**Comment by jonahshader** [comment]
This is an issue with the WallPanel so I added it there: [https://github.com/micro-nova/AmpliPiWallPanel/issues/22](https://github.com/micro-nova/AmpliPiWallPanel/issues/22)
