### ISSUE TITLE
Bug: Api docs fail to seperate different stream commands 

### ISSUE THREAD

**Issue by marc-portier** [micro-nova/AmpliPi#368]
When one tries out the Stream 'Exec Command' endpoint (i.e. `POST /api/streams/{sid}/{cmd}`) through the available front-end testing page at [/doc](http://amplipi.local/doc) one can not select just one value from the enum - clicking any of them fills them all into the field

See screenshot:

![image](https://user-images.githubusercontent.com/299574/186009310-fc63cf48-a09b-45ef-82f1-ab482282470f.png)

Observation applies to firmware version 0.1.8

**Comment by linknum23** [comment]
This is a bug in the api viewer tool we use, We should try using a more recent one soon to see if this is fixed.

**Comment by linknum23** [comment]
This appears to be fixed in the latest release of rapidoc. We should be able to integrate a fix for this in the next release.
