### ISSUE TITLE
Add LMS Metadata and control

### ISSUE THREAD

**Issue by linknum23** [micro-nova/AmpliPi#405]
A simple command control interface implementation can be found here: 
https://github.com/samtherussell/squeezebox-controller

- [ ] Test basic control interface in a python repl
- [x] Test server discovery: https://github.com/ralph-irving/squeezelite/blob/master/tools/find_servers.c
Output on our network with a couple of lms servers running, takes ~1sec
- [x] Make metadata script to poll server and save json to a file. Partial test script below
```
SERVER="192.168.0.106"
SERVERPORT="9000"
MACADDR="6a:37:f9:d8:59:fb" # player "MAC"

TRACKID=$(curl -g -X POST -d '{"id":1,"method":"slim.request","params":["'$MACADDR'",["'status'","-",1]]}' http://$SERVER:$SERVERPORT/jsonrpc.js 2>/dev/null |jq -r ".result.playlist_loop[].id")

SONGINFO=$(curl -g -X POST -d '{"id":1,"method":"slim.request","params":["'$MACADDR'",["'songinfo'","-",100,"'track_id:$TRACKID'"]]}' http://$SERVER:$SERVERPORT/jsonrpc.js 2>/dev/null)

echo $SONGINFO | jq -r  ".result.songinfo_loop[]" | jq -s add 

# NOTE: url can be recovered from coverid if local
# URL=http://$SERVER:$SERVERPORT/music/$COVERID/cover.jpg
```
- [ ] Integrate controls into amplipi/streams.py
- [x] Add json metadata reading to streams.py

**Comment by linknum23** [comment]
We will probably want to add support for #413 as well

**Comment by sumnerboy12** [comment]
I am trying to run LMS in Docker with a Traefik reverse proxy in front - so it would be handy to have the option to specify the LMS server and port when setting up the LMS client on my AmpliPi. It looks like the code in `streams.py` looks for a `server` config parameter but I can't see how to specify this in the UI?

**Comment by linknum23** [comment]
Moved this to a separate issue: #451
