### ISSUE TITLE
Wall-Keypad hard-buttons visible in Sonoff EweLink app

### ISSUE THREAD

**Issue by rickballard** [micro-nova/AmpliPi#406]

**Comment by linknum23** [comment]
As far as we know supporting anything in the Sonoff EweLink App ecosystem is not possible as **none** of Sonoff's proprietary software needed to work with the app exists on the wall panel we ship. The wall panel shipped has been programed with our own completely open source firmware that only "knows" how to talk to AmpliPi.

That said we realized that everyone that has one of these wall panels would want to be able to use the remotely control these switches in their smart home ecosystem and added MQTT support for each of the switches. Here is a guide on how to add the buttons to HomeAssistant: https://github.com/micro-nova/AmpliPiWallPanel/#setting-up-mqtt-with-home-assistant.
