### ISSUE TITLE
Bug: Update available after updating to latest

### ISSUE THREAD

**Issue by linknum23** [micro-nova/AmpliPi#408]

**Comment by linknum23** [comment]
This is a artifact from a hotfix that we did to the 0.1.9 version. The github tag is 0.1.9+uv-hotfix. In the future it probably makes sense to just update the tag. Lets make a 0.1.10 release soon to fix this.

**Comment by Lohrer** [comment]
Would it make sense to have the next release be 0.2.0 so we can use the third field for hotfixes and such?

**Comment by linknum23** [comment]
Yeah. That would make this a lot easier.
