### ISSUE TITLE
Tweak Play Control buttons

### ISSUE THREAD

**Issue by linknum23** [micro-nova/AmpliPi#417]
- [ ] Reduce spacing between buttons
- [ ] Switch between thumbs up and heart for pandora and spotify

![Screenshot_20221220-074918_AmpliPi](https://user-images.githubusercontent.com/628667/208773634-1add1277-6d3c-4b85-ac90-dad645e89f95.jpg)

**Comment by linknum23** [comment]
Needs to CSS work to polish this interface for narrow screens.

**Comment by SteveMicroNova** [comment]
We no longer have this interface, I did briefly recreate this issue on the new one but have since solved that. Closing this as completed.
