### ISSUE TITLE
Link to 0.1.7 release download is broken

### ISSUE THREAD

**Issue by hawkeye312** [micro-nova/AmpliPi#422]
https://github.com/micro-nova/AmpliPi/releases/download/0.1.7/amplipi-update-0.1.7.tar.gz

Trying to update my firmware which does not yet have the auto-update feature.

**Comment by linknum23** [comment]
Sorry about that. We'll fix that soon. There was an issue we had to patch
on all releases and we removed old releases to make it easier.

You should use the 0.1.9 release instead. Here's a link:
https://github.com/micro-nova/AmpliPi/archive/refs/tags/0.1.9-uv-hotfix.tar.gz

Just a heads up, automatic updates are not available yet, however the
updater was improved significantly.

**Comment by linknum23** [comment]
Working on this here #423. Looks like main is a little behind on some of our fixes to keep our continuous integration satisfied.
