### ISSUE TITLE
RTL-SDR source playing only from left channel

### ISSUE THREAD

**Issue by vmooney** [micro-nova/AmpliPi#454]
Only left channel plays the FM radio. Happens on all audio outputs except Source 1.

**Comment by linknum23** [comment]
Hmm that is odd. Do other audio sources work fine on sources 2-4? Have you tried rebooting the system?

**Comment by vmooney** [comment]
Yes other audio sources work fine on 2-4 such as the Groove Salad demo stream and analog inputs.

I don't ever recall it working, issue persists across reboots and multiple versions of AmpliPi (currently running v0.2.1)

**Comment by linknum23** [comment]
Hmm that is odd. Admittedly it has been awhile since we tested the USB SDR
but I don't recall this issue. I'll check if this happens on our unit and
report back.
