### ISSUE TITLE
Give the new UI a once-over for fit & finish before marking it 'stable'

### ISSUE THREAD

**Issue by rtertiaer** [micro-nova/AmpliPi#478]
- [x] `eslint` all React
- [x] implement `eslint` in Github Actions
- [x] Create custom build with ElasticAPM/Sentry/etc frontend JS traceback collection and abuse it
- [x] Look for, file & fix any bugs discovered in the process.

Since 2/3 of the checkboxes here do not have a well-defined stop point, we'll go based on feeling or time elapsed for those.

**Comment by rtasson** [comment]
@SteveMicroNova and I had discussed using ElasticAPM RUM in a temporary fashion to hash out bugs. However, after talking this out with Lincoln, I'm pretty sure it makes sense to implement it as an opt-in debug configuration.

Last commit I see [here](https://github.com/micro-nova/AmpliPi/compare/Webapp2-RUM) is [f810437cee](https://github.com/micro-nova/AmpliPi/commit/f810437cee96f482d2996549737b4654235b4749); I'll pick this up from there and run with it.

**Comment by rtertiaer** [comment]
I'm closing this particular ticket, with #467 being merged (even though we're still just on release candidates of 0.3.0, it's actual launch.)
