### ISSUE TITLE
UI Feedback

### ISSUE THREAD

**Issue by SteveMicroNova** [micro-nova/AmpliPi#495]
Meta issue for feedback related to the new UI

- [x] #350 
- [x] #405 
- [x] #496
- [x] #497
- [ ] #498
- [x] #499
- [ ] #500
- [ ] #501
- [ ] #529 
- [ ] #554
- [ ] #555  
- [ ] #556 
- [x] #572
- [x] #574 
- [x] #590 
- [ ] #580 
- [x] #586 
- [ ] #604
- [ ] #605
- [ ] #606
- [ ] #607
- [ ] #617
- [ ] #637
- [ ] #705 
- [x] #712 
- [ ] #713 

This one is old but still relevant to the new ui
- [ ] #326

**Comment by Lohrer** [comment]
- Internet radio:
  - Pressing enter on search doesn't search
  - If no stations are found there is no indication that a search was actually performed (at least I think that's what's happening, or maybe it's just not working sometimes? I don't know, there's no status so I don't know what's going on).
  - Search results selection: There is no indication of which station is actually selected after clicking on one of the search results.
  - Inconsistent naming: "logo" should be capitalized to "Logo" to match the other fields. To be consistent "url" would be "Url" but that's weird so it should probably be "URL".
  - Nice-to-have: after entering a logo on the Internet Radio stream creation modal, it would be awesome to see that logo as a thumbnail next to the "logo" text.
  - Nice-to-have: All the text fields including the two URL sections are fixed-width. It would be very helpful to have them expand to the width of the modal.
- There is no playing/paused/stopped status on the "Home" view, so it's impossible to see which streams are actually playing without 3 clicks per enabled stream.
- Should we replace the text under "HW reboot" from "Raspberry Pi-based controller" to Embedded Linux controller or something? Or are we not caring about removing RPi from branding?
- There's a dot on the settings icon when an update is available, but there's nothing to inform the user that that's what the dot actually means. Maybe add a dot next to updates after selecting the settings page?

**Comment by linknum23** [comment]
I added all of those as issues. Thanks for the feedback @Lohrer

**Comment by SteveMicroNova** [comment]
With many of these UI issues we ought to bias towards using [MaterialUI](https://mui.com/material-ui/) since that's a package we already use and has premade components that can do what we need, such as the [snackbar component](https://mui.com/material-ui/react-snackbar/)'s ability to function as a notification/warning popup, something that covers at least two of the issues on this list

**Comment by rtertiaer** [comment]
I've assigned a label of usually `webapp` and sometimes `user-experience` to this. This ticket should not be maintained moving forward. Please use tags.
