### ISSUE TITLE
WebApp2 - Make streams swappable from the player screen

### ISSUE THREAD

**Issue by SteveMicroNova** [micro-nova/AmpliPi#496]
The whole idea is in the title, but the justification for it is this:

I envision amplipi as having a primarily domestic usecase, standard family stuff so that there can be a stream for each bedroom and one for shared areas (assuming the standard nuclear 2 parents 2 kids setup where each kid has their own room). In that case where there's a dedicated stream for specific zones at all times, there's no real reason to go to the home view except to change what source you're controlling on the player view, so unless you want to change the shared zones in this hypothetical usecase, the user will 99.99% of the time only be using the player view that points to their own dedicated stream that plays in their room
This feature makes the player page more useful, requiring one click to open the change streams dialog instead of the 2-3 it would've taken otherwise

**Comment by SteveMicroNova** [comment]
This has been completed in develop since roughly August 30th, for some reason it wasn't autoclosed when that branch was merged but it is done

**Comment by linknum23** [comment]
These won't auto close until merged into main.
