### ISSUE TITLE
Make settings tabs more consistent style wise

### ISSUE THREAD

**Issue by SteveMicroNova** [micro-nova/AmpliPi#498]
(Ex: every settings page has an X in the top right to go back to the settings page, but the Updates page has [<- Back to App] button in the top left instead, Configuration has the wrong font)

**Comment by SteveMicroNova** [comment]
Since writing this issue, I've been made aware that the Updates page may be separate and different on purpose, I'd like to affirm whether or not we want to actually change it @linknum23

Changing it would require either merging it into our current react app so it can make use of the same stylings, or making it into its own react app and copying a lot of the same style info over

**Comment by linknum23** [comment]
The updater is a completely separate app. Migrating it would be a fair amount of work.
 I like the idea of making it look pretty like our current UI, but I think we may want to wait on our changes to the updater for imaging to avoid doing extra work.

**Comment by SteveMicroNova** [comment]
> I think we may want to wait on our changes to the updater for imaging to avoid doing extra work.

Got it, splitting this issue out and adding the Updater page portion to #780
