### ISSUE TITLE
Add a check for if a stream is already being played before it can be added to another source

### ISSUE THREAD

**Issue by SteveMicroNova** [micro-nova/AmpliPi#501]
Add a check for if a stream is already being played before it can be added to another source so that you can't accidentally steal music from others (Bonus points if you make the chosen zone tune in to the source already playing the stream)

**Comment by SteveMicroNova** [comment]
This will likely be complimented by #500, so that you can tune in and also not be effected when they change the top level volume

That said, this is possibly easier than #500 unless it ends up like the linked PR to #500 where I find that you have to go elbow deep into the core of AmpliPi to achieve it

**Comment by rtertiaer** [comment]
We should also ensure that when we do this, the stream does not get reset. This should function like clicking the zone button on a stream card.
