### ISSUE TITLE
Update GIFs used to demonstrate Web UI

### ISSUE THREAD

**Issue by linknum23** [micro-nova/AmpliPi#537]
These [GIFs](https://github.com/micro-nova/AmpliPi/tree/0.3.0-beta2/docs/imgs/app_demos) need to be updated to the latest UI. Try following this [guide](https://github.com/micro-nova/AmpliPi/blob/0.3.0-beta2/docs/imgs/app_demos/HOW_TO.md). Ping @linknum23 for help.

**Comment by SteveMicroNova** [comment]
Merged with develop, issue solved
