### ISSUE TITLE
React error on player tab

### ISSUE THREAD

**Issue by SteveMicroNova** [micro-nova/AmpliPi#553]
![image](https://github.com/micro-nova/AmpliPi/assets/114415937/1a1b4733-2b87-4037-bfc1-3feae4f6e542)

If you have a player page open and the player you’re on is closed by another user, you get a react error
It would probably be better to display “No Player Selected!” Or just kick them back to the home page in this instance
Maybe use a [MaterialUI (React library) snackbar component](https://mui.com/material-ui/react-snackbar/) to explain to the user what happened as well so it doesn’t appear like a glitch when they’re booted / the content goes missing

**Comment by linknum23** [comment]
I like the idea of an adding an explanation

**Comment by SteveMicroNova** [comment]
With the creation of my automatic stream selection, this is fixed
In cases where there are no other streams to select, this page just says "No player selected!" so that is doubly fixed.
