### ISSUE TITLE
No confirmation dialog for options on config page

### ISSUE THREAD

**Issue by gorski123** [micro-nova/AmpliPi#580]
When uploading a new config, resetting the box back to factory config, performing a HW reset, etc, It would probably be a good idea to first show a pop-up dialog confirming the choice. Then there should be some type of spinner while the action is performed, followed by some type of confirmation that the selected action has been completed.

**Comment by SteveMicroNova** [comment]
This should be fairly easy to achieve, we already use the React library that contains a [loading spinner](https://mui.com/material-ui/react-progress/#circular)

I'm not able to spend time to this rn but there's the solution for whenever someone takes on this issue

**Comment by rtertiaer** [comment]
probably deserve to do the same with LMS mode, particularly beause it downloads some config
