### ISSUE TITLE
Search for Pandora stations during stream creation, like the internet radio search

### ISSUE THREAD

**Issue by rtertiaer** [micro-nova/AmpliPi#602]
Lincoln believes a lot of this functionality is built into Pianobar already, and we just need to expose it.

**Comment by linknum23** [comment]
The simplest way to get the station list without playing is to configure the station wrong, have pianobar print out the station list, and provide that to the user. 

After a station is selected by index we can use the number printed (station-id) to populate the stream field. 

My initial suggestion for this is to provide a method in the pandora stream class for getting the station list when a stream is not playing that uses /dev/null as the audio output.

```
link$ pianobar 
Welcome to pianobar (2019.02.14)! Press ? for a list of commands.
(i) Control fifo at /home/link/.config/pianobar/ctl opened
(i) Login... Ok.
/!\ Error: Autostart station not found.
(i) Get stations... Ok.
         0) q   2013 Top Alternative Radio
         1)     60s, 70s, and 80s Hits Radio
         2)     70s Rock Radio
         3)     90s Alternative Radio
         4) q   Airplanes Radio
         5)     AJR Radio
         6)     ALT XL: Today's Alternative Radio
         7) q   Ambient Radio
         8) q   Arcade Fire Radio
         9)     Band Of Horses Radio
        10)     Big Band Radio
        11)     Brunch Radio
        12) q   Cake Radio
        13)     Candy Cane Lane Radio
        14) q   Christmas Radio
        15) q   Christmas Traditional Radio
        16)     CHVRCHES Radio
        17) q   Cinco de Mayo  Radio
[?] Select station: 16
|>  Station "CHVRCHES Radio" (3679043843127675840)
(i) Receiving new playlist... Ok.
|>  "Recover" by "CHVRCHES" on "The Bones of What You Believe"
```

I realize that the steps above are a little roundabout. Another way to do this is to find a js implementation of a pandora api client that can browse for this type of thing from the user side. There is also a python api for pandora called pydora if we want to implement this server side without pianobar: https://pypi.org/project/pydora/.
