### ISSUE TITLE
Hide FM Radio option when no hardware is plugged in

### ISSUE THREAD

**Issue by rtertiaer** [micro-nova/AmpliPi#631]
One can configure an FM Radio stream even if there is no hardware plugged in. This is a bit confusing, because it implies the AmpliPis have built-in FM radio receivers. Remove this option if there is no receiver plugged in.

**Comment by linknum23** [comment]
Should existing FM streams also be shown as unavailable/disabled when no hardware is available?

**Comment by rtertiaer** [comment]
I like that. It's not clear how we should best communicate that to the user thru the UI/interaction, but we ought not hide existing configs, just disable them.
