### ISSUE TITLE
Default Passwords Too Long for E-Ink Display

### ISSUE THREAD

**Issue by SteveMicroNova** [micro-nova/AmpliPi#676]
![image](https://github.com/micro-nova/AmpliPi/assets/114415937/d5f716d6-9206-4ad8-aa3c-59d460ec21be)
See image, the character limit for default passwords is at least one off to fit on the new display

**Comment by SteveMicroNova** [comment]
This may be an issue with this the E-Ink or it may be an issue with how this specific board was mounted, we're also looking into better QA on E-Ink mounting as a solution to this issue as the image looks like the board is shifted about a character worth of space to the right

**Comment by SteveMicroNova** [comment]
#677 is related

**Comment by rtertiaer** [comment]
I think this is actually just hte mounting on this particular box being off a smidge and am inclined to close this.

**Comment by rtertiaer** [comment]
#677 obsoletes this ticket; closing.
