### ISSUE TITLE
Maybe Use Compute module 4 for more power

### ISSUE THREAD

**Issue by jarno9981** [micro-nova/AmpliPi#68]
Maybe idee for next version compute module 4 from raspberry pi

**Comment by mabowers** [comment]
Hey @jarno9981!

Bumping to the CM4 would be great for a future version. The biggest thing stopping us from using the CM4 right now is that it is not yet readily available in high quantities (and given the global semiconductor shortage, it might not be available for quite a while yet.) The good news is, the CM3+ we use now is already pretty overkill for this role. In our testing, playing back four simultaneous stereo audio streams from a mix of streaming sources/protocols only uses around 10-20% CPU, leaving plenty of CPU overhead for future use 🙂

The CM4 will be nice for a variety of reasons. The A72 cores are awesome, having dual 4K HDMI with H.265 hardware decoding would be really awesome for using AmpliPi as a HTPC, and having a PCIe interface to work with would add a lot of flexibility. Our plan as AmpliPi evolves is to offer reasonably-priced upgrade boards that will be backwards compatible with existing units in the field. For example, we could offer a new version of the control board with a CM4 that would be a drop-in replacement for the existing control board. (Same goes for future versions of the amplifier and pre-amp boards.) We are working on some final changes to the electrical design and case mechanics to better support such upgrade boards. Unlike most consumer electronics that are "throwaway" after a few years (or after a new standard comes out), we want AmpliPi to be a long lasting and environmentally friendly design that can be serviced and upgraded for many years to come!
