### ISSUE TITLE
Be more gentle with testing external services

### ISSUE THREAD

**Issue by rtertiaer** [micro-nova/AmpliPi#706]
We have bumped up against IP bans and rate limits when running AmpliPi tests that interact with external services. We should be more gentle with these. Some potential paths forward:
* Segment these tests away from other tests
* Only run these tests on releases or merges to main (this won't fix IP limiting, but would for account limiting)
* Make these tests hit the external services less intensely

The service we encountered this the most with is Pandora, but we really should be gentle with all external services in this way.

**Comment by linknum23** [comment]
This happened again today

**Comment by linknum23** [comment]
It breaks my pandora client and makes it so I have to load like 500+MB of a chrome tab :sob:

**Comment by rtertiaer** [comment]
#730 is one PR that can help address this, tho it's unclear if it will completely close this issue.

**Comment by linknum23** [comment]
We will reopen this if necessary.
