### ISSUE TITLE
Make quickstart QR code valid; put to e-ink display during manufacturing

### ISSUE THREAD

**Issue by rtertiaer** [micro-nova/AmpliPi#718]

**Comment by gorski123** [comment]
Issue #677 should get tied in with this as well

**Comment by rtertiaer** [comment]
I've put in PR #728 . Additionally, I've fixed the URL redirect for https://amplipi.com/getting-started. At present, it just points to the manual; I've set a remainder for myself oob when the quick start video launches to change this redirect to it.
