### ISSUE TITLE
Make streams easy to reset and stop

### ISSUE THREAD

**Issue by linknum23** [micro-nova/AmpliPi#729]
### Context

In AmpliPi a stream is defined as any type audio input that can be played on a source in the system. To play audio out a zone a stream needs to be connected to a source with one or more zones. 

Steams come in a couple of different flavors. Some streams hold their state and implement the PersistentSream interface, others just implement the BaseStream interface. To reset a PersistentSream it needs to be deactivated and then activated. To reset a  BaseStream disconnecting and connecting it from a source provides a full reset.

### Problem

Sometimes a stream gets into a bad state and needs to be restarted. How to do this is not obvious at either an API level or from the UI. For the API it even depends on what type of stream it is.  

### Solution

- Add a `api/streams/{sid}/reset` endpoint to make unified reset interface
- Add a UI view in settings that allows running streams to be reset (and stopped?)
- Optional: add a button in the player view to reset a stream as well?

**Comment by mjustian** [comment]
What should happen to a PersistentStream that doesn't support activation/deactivation?

**Comment by linknum23** [comment]
I'm guessing you are talking about:

```
  def _activate(self, vsrc: int):
    raise NotImplementedError(f'{self.stype} does not support activation')
```

This is the pythonic way of creating an abstract class. Any stream that implements PersistentStream should implement those.

**Comment by mjustian** [comment]
Should this restart an MP3 stream to the beginning?

**Comment by linknum23** [comment]
Yup. Realistically that stream is used mostly for announcements. It should work like the reset of streams though to keep a similar user experience.

**Comment by sumnerboy12** [comment]
Is this implemented in v0.3.6 as `restart`;

![image](https://github.com/micro-nova/AmpliPi/assets/5060842/1f0f6a97-8d5f-4fde-840e-f23af055117e)

**Comment by linknum23** [comment]
Yup it got included. There's even a button to do it in the UI in `Settings->Streams`:. To use it select a stream and click the reset button at the bottom of the stream configuration modal..

**Comment by linknum23** [comment]
The meat of this issue is implemented, closing...
