### ISSUE TITLE
Pianobar is having trouble opening audio device

### ISSUE THREAD

**Issue by gorski123** [micro-nova/AmpliPi#739]
[Pianobar](https://github.com/PromyLOPh/pianobar) the underlying client we use to play Pandora streams appears to sometimes be unable to open the audio device. The user will see this as a Pandora stream that will stop playing audio. Switching streams or using the Pandora station browser to switch to a different station will usually fix the problem. Here is a log from pianobar:

```
pi@amplipi-inhouse:~/amplipi-dev/config/srcs $ cat v1/.config/pianobar/output 
Welcome to pianobar (2019.02.14)! Press ? for a list of commands.
(i) Control fifo at /home/pi/amplipi-dev/config/srcs/v1/.config/pianobar/ctl opened
(i) Login... Ok.
(i) Get stations... Ok.
|>  Station "Regina Spektor Radio" (189553607752814248)
(i) Receiving new playlist... Ok.
|>  "On the Radio" by "Regina Spektor" on "Begin To Hope (U.S. Version)"
/!\ Cannot open audio device.
|>  "You And I" by "Ingrid Michaelson" on "Be OK"
|>  "1234" by "Feist" on "The Reminder (Deluxe Version)"
|>  "New Soul" by "Yael Naïm" on "Yael Naïm"
pi@amplipi-inhouse:~/amplipi-dev/config/srcs $ cat v1/.config/pianobar/error 
ALSA lib pcm_dmix.c:1165:(snd_pcm_dmix_open) unable to open slave
```

Currently we are not sure if this happens mid song, when starting up, or when changing songs, or some combination. Current thoughts are our virtual sources are possibly interfering with pianobars behavior / expectations. 

This was the original reason we had tried to add a process monitor to pianobar.
Current thoughts are we could fork pianobar and attempt to make the changes to the source ourselves. Other options are https://deviousfish.com/pianod/ and pydora as replacements for pianobar.

**Comment by rtertiaer** [comment]
I'm adding this to the 0.4.x board to triage before our next meeting.

**Comment by linknum23** [comment]
One solution to this problem may be to build the latest pianobar release from source. Currently the deb package is at least several years out of date.

**Comment by linknum23** [comment]
Our current version is 2019.02.14, there have been 3 releases since then, the latest being: 2022.04.01. Source https://github.com/PromyLOPh/pianobar/blob/master/ChangeLog

**Comment by klay2000** [comment]
Just noting here that Pianod (https://deviousfish.com/pianod/) is based on pianobar, so we probably shouldn't switch to that.

**Comment by klay2000** [comment]
update to this:
updating pianobar didn't help, it broke the same way


![Image](https://github.com/micro-nova/AmpliPi/assets/5252693/e37b9acf-cdeb-46be-bc56-5febe168f007)

**Comment by linknum23** [comment]
Since pianobar doesn't see a lot of development it might not be too risky
to maintain our own fork. There might be an easy fix. See
https://github.com/PromyLOPh/pianobar/blob/caf14ba90b9aca483d13dff12d03af48dd6936b6/src/player.c#L548

**Comment by klay2000** [comment]
[So I forked pianobar and made a couple changes to the current release version](https://github.com/PromyLOPh/pianobar/compare/master...klay2000:pianobar:master), built it and replaced the binary on the inhouse amplipi and it seems like it's more stable. I'm going to let it run over the weekend but my question now is what should we do, try to get this change merged into pianobar or maintain a fork ourself?

**Comment by gorski123** [comment]
Can we do both?

**Comment by rtertiaer** [comment]
the updated link for changes between forks is https://github.com/PromyLOPh/pianobar/compare/master...micro-nova:pianobar:master
