### ISSUE TITLE
Use a RAM disk for volatile configuration

### ISSUE THREAD

**Issue by linknum23** [micro-nova/AmpliPi#76]
AmpliPi uses an mmc on board the Pi Cm3+. To reduce the wear on the mmc, we should configure any volatile writes to use a RAM disk. Almost all of the stream config should be moved to this.
- [x] RAM directory creation at startup
- [x] Add pertinent config and metadata files to RAM
- [x] Figure out how much space is needed for the partition (100 MB or smaller)

**Comment by micronova-jb** [comment]
See #119
