### ISSUE TITLE
Version-checking in both the updater and main app report incorrect latest

### ISSUE THREAD

**Issue by rtertiaer** [micro-nova/AmpliPi#798]
My 0.4.0 box insists there's a new update, 0.4.0 - but only upon refresh. 

The backend reports the latest is still 0.3.6 in the /api endpoint. This might just take a second, but I'd like to not lose track of that so I'm reporting it here as well.

**Comment by linknum23** [comment]
At the moment the latest release is checked once a day at 5am EST. We could probably increase the frequency on this. 

To actually fix this specific issue, we may want to run the `check_release` script after an update.
