### ISSUE TITLE
"Add Stream" button misaligned on Firefox

### ISSUE THREAD

**Issue by jonahshader** [micro-nova/AmpliPi#803]
Chrome:
![image](https://github.com/micro-nova/AmpliPi/assets/4961732/9009c016-5645-4f5f-b315-92a18a0d234f)
Firefox:
![image](https://github.com/micro-nova/AmpliPi/assets/4961732/30496de7-557e-406d-8da2-8da11de0dba5)

**Comment by rtertiaer** [comment]
I think this was fixed in #800 , when I swapped the font families. I'll confirm when that PR makes it into a release.

**Comment by rtertiaer** [comment]
Yeah, this is fixed.
