### ISSUE TITLE
Button color

### ISSUE THREAD

**Issue by SteveMicroNova** [micro-nova/AmpliPi#809]
Somewhere between now and the 0.4.0 release there's been a change to main that changes the color of all buttons grey
See before and after below

Before:
![image](https://github.com/user-attachments/assets/151b29df-14cd-40b7-9aa2-e3a6d9788109)
![image](https://github.com/user-attachments/assets/12b35f5c-84e7-4c89-94b6-ed5d9c4d859c)

After:
![image](https://github.com/user-attachments/assets/8b982d0b-993b-4484-8fcf-487dc0c662aa)
![image](https://github.com/user-attachments/assets/dc1f4c60-2c1e-44a9-8c98-af254df928e6)

**Comment by SteveMicroNova** [comment]
Note that these buttons aren't inactive, simply discolored

**Comment by rtertiaer** [comment]
This is as a result of #800 ; if you'd like, you can modify the theme for this ticket. The blue that it was using prior was not stylistically consistent with the rest of the things, but "grey" is the only theme my colorblind self could pick that was sane-ish.

**Comment by linknum23** [comment]
I would vote for buttons being having some color. Grey buttons look like they are disabled.
