### ISSUE TITLE
FM Radio only outputs to left speaker

### ISSUE THREAD

**Issue by SteveMicroNova** [micro-nova/AmpliPi#810]
https://amplipi.discourse.group/t/fm-radio-is-in-mono/310/4

Found by a discourse user, tested in house, FM radio is transmitted in Mono but for some reason it only goes to the left speaker rather than both

**Comment by linknum23** [comment]
For reference this was previously fixed here:
https://github.com/micro-nova/AmpliPi/pull/455. We should figure out what
got broken.

Stuff like this really points at us needing a human in the loop play all of
the basic stream types script, with the human validating that we get good
audio and metadata for each.

**Comment by rtertiaer** [comment]
I was not able to replicate this on my appliance.

**Comment by SteveMicroNova** [comment]
> I was not able to replicate this on my appliance, playing [101.9 WDET](https://wdet.org/) 😎

Interesting, the inhouse unit did replicate this with both [100.3 WNIC](https://wnic.iheart.com/) and [94.7 WCSX](https://wcsx.com/)
What differences can we draw between our units? Is yours a streamer? Is your usb dongle somehow better? Is it something about the speakers, using RCA out instead of the pheonix connectors maybe?

**Comment by SteveMicroNova** [comment]
I've walked around the office to check both units, here's my findings:

> Is yours a streamer?
No

> Is your usb dongle somehow better?
No, it is in fact the exact same. Not even just the same model, the same antenna itself.

> Is it something about the speakers, using RCA out instead of the pheonix connectors maybe?
This is my bet, the inhouse only uses pheonix (amplified) and your test unit uses RCA out (preout) connections

**Comment by Pedalnetics** [comment]
I am using the Phoenix connectors and getting Mono audio (I am the original poster in the forums who hit this issue).

**Comment by rtertiaer** [comment]
our new QA process has replicated this as well

**Comment by klay2000** [comment]
this appears to only happen on source 0
