### ISSUE TITLE
Make the display service work when the API is authenticated

### ISSUE THREAD

**Issue by rtertiaer** [micro-nova/AmpliPi#812]
post #799 , it feels like the proper fix here is actually to bypass auth for any requests on localhost.

**Comment by linknum23** [comment]
I like this idea

**Comment by rtertiaer** [comment]
cross-post: actually, simply checking the `Host` header invites us to [header smuggling attacks](https://www.intruder.io/research/practical-http-header-smuggling). I'm gonna implement a better methology for the display server instead - we can rely upon our `auth` module in the non-`configure.py` case 😎
