### ISSUE TITLE
No scroll feature under "Streams" while on safari 

### ISSUE THREAD

**Issue by mrahman313** [micro-nova/AmpliPi#834]
Check out the video below. 

I have to zoom out on safari to click on spotify if I want a stream.

**Comment by mrahman313** [comment]
Uploading RPReplay_Final1722007064.mp4…

**Comment by mrahman313** [comment]
Uploading RPReplay_Final1722007064.mp4…

**Comment by mrahman313** [comment]
https://github.com/user-attachments/assets/ae3fafde-6e8e-40c7-bc03-affe1c422d61

**Comment by rtertiaer** [comment]
duplicate of #833

**Comment by rtertiaer** [comment]
wait, I'm wrong.
