### ISSUE TITLE
Upgrade to go-librespot

### ISSUE THREAD

**Issue by rtertiaer** [micro-nova/AmpliPi#876]
Our Discourse user Nate had a couple of issues running Spotify Connect; we should attempt to investigate, replicate and resolve any bugs we find that look anything like this person's experience.

ref: https://amplipi.discourse.group/t/amplipro-streamer-first-impressions/320?u=amplipi

**Comment by klay2000** [comment]
I attempted to replicate this the day that post was made and I could not replicate it on the version of spotifyd we ship on the box for arm, however the x64 build (probably not as recently updated) does present similar issues.
