### ISSUE TITLE
Feature: Plexamp for Raspberry Pi

### ISSUE THREAD

**Issue by micronova-jb** [micro-nova/AmpliPi#92]
- [x] Test Plexamp v1 with MPD and make any required changes
- [x] Created Plexamp stream class and config handler (server.json/mpd.conf)
- [x] Find out a better way to handle user information in server.json (potentially not required for a simple audio endpoint)
- [x] Song metadata? <- Handled atypically in Plex, and seemingly unavailable until a newer, headless version
- [x] Create documentation on how to use plexamp on AmpliPi
- [x] Implement install process
     - [x] Packaging our changes with plexamp v1 for initial install
     - [x] Adding reqs to configure script (uuid-runtime, node 9 install)
     - [x] "Pin" nodejs at version 9.11.2
- [x] Implement Plex account connection in WebApp

I've put some work into adding Plexamp support for the AmpliPi system - this issue will detail my findings.

- The current state of support:
As of right now, the AmpliPi system shows up as a local device to cast to from Plexamp/Plex on cellphone or desktop. This thread marks the beginning of my search for answers: https://forums.plex.tv/t/selecting-the-alsa-device-that-plexamp-outputs-to-on-raspberry-pi-cm3/692189

Thanks to odinb1's efforts (detailed here: https://github.com/odinb/bash-plexamp-installer) I was able to reach the current state. You can install plexamp on the Pi using their script, or you can follow the official install guide here: https://forums.plex.tv/t/plexamp-for-raspberry-pi-release-notes/368282

Be sure to include the workaround that OttoKerner linked in the post above. In either guide, you will have to edit the server settings @ /home/pi/.config/Plexamp/server.json. Odinb1 talks about this on their GitHub README.md - you'll have to get a working copy of server.json from an old desktop version of plexamp.

- What's missing?
Check out both of my forum posts ([1](https://forums.plex.tv/t/selecting-the-alsa-device-that-plexamp-outputs-to-on-raspberry-pi-cm3/692189) and [2](https://forums.plex.tv/t/configuration-settings-for-playing-audio-on-a-specific-channel-of-a-usb-audio-device-connected-to-raspberry-pi/696974)) to get the bigger picture of where we're at. Currently, there doesn't seem to be a way to specify channels for plexamp. This is problematic, given the fact that every other source we provide has the ability to specify a channel (which is set in asound.conf). The de-obfuscated javascript for the RPi version of plexamp can be found here: https://gist.github.com/micronova-jb/c7bc03ae046ce6ce988d3062555ed6e3

Perhaps there's something hidden in there that we haven't been able to find - for now, plexamp plays on ch1, ch2, and ch3 when cast to. These are the channels associated with the USB sound card.

I will try to keep this issue up to date as more information comes out!

EDIT 3/30/21: Jason and I are both in an external channel of the Plexamp Slack. Elan recommended an earlier version of headless plexamp for Pi (ver. 1.x), so I'm trying that now. I don't see any differences so far.
https://files.plexapp.com/elan/plexamp-v1.0.5-pi.tar.gz

EDIT 4/19/21: The older version of Plexamp is working! We had to make some tweaks to the javascript (after de-obfuscating), but you are now able to select an audio device! We're still unable to get multiple running at the same time - it seems like this will take significant changes to the plexamp software.

EDIT 5/4/21: Gist of the file actually being used on the AmpliPi (difficult to read because it is fully obfuscated and on one line)
https://gist.github.com/micronova-jb/1156b1d04639284e5c6a354de4ec3002

De-obfuscated version:
https://gist.github.com/micronova-jb/e66e4a78ad3feaa655c292de64c189cd

Look for the specific changes around lines 25200 - 25205 in the de-obfuscated file. Basically, we have to tell it to use the MPD configuration, taking the device name. In mpd.conf, the audio device can be selected (e.g. ch2)

EDIT 5/12/21: Check out the new forum post - I detailed some more of the process here: https://forums.plex.tv/t/configuration-settings-for-playing-audio-on-a-specific-channel-of-a-usb-audio-device-connected-to-raspberry-pi/696974/11

**Comment by linknum23** [comment]
@micronova-jb you should update this with the currentstate

**Comment by micronova-jb** [comment]
https://files.plexapp.com/elan/plexamp-v1.0.5-pi.tar.gz

Adding the plexamp version we're running on the Pi

**Comment by micronova-jb** [comment]
Seems to want to automatically run a plexamp instance with "AmpliPi-Template"
This should be removed

**Comment by micronova-jb** [comment]
Notes on setup (port to documentation later):
Before running the deploy script, be sure to replace "server.json" in the streams directory with the file of the same name from the alternate plexamp install (odinb's RPi plexamp guide). This mainly ensures that [user][id] and [user][token] are properly captured, so you can simply take these values if you prefer. Without this step, plexamp won't work!

**Comment by micronova-jb** [comment]
Need to make sure the streams.py line "plexamp_args = '/usr/bin/node /home/pi/plexamp/server/server.prod.js'" will actually work. When extracting the plexamp tar.gz, make sure the contents end up in /home/pi/plexamp/ (or we can change this line to a better location)

The current example actually allows you to pass a token and id if the proper one wasn't copied over. This is a bit more cumbersome, so proper copying is preferred (this just offers a server-side option)
